"""initial schema

Revision ID: 079f7107662b
Revises: 
Create Date: 2026-07-11 14:29:19.804627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '079f7107662b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), server_default='password', nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('wall_width', sa.Numeric(), nullable=False),
    sa.Column('wall_height', sa.Numeric(), nullable=False),
    sa.Column('wall_unit', sa.String(), nullable=False),
    sa.Column('ruler_length', sa.Numeric(), nullable=False),
    sa.Column('ruler_visible', sa.Boolean(), nullable=False),
    sa.Column('ruler_color', sa.String(), nullable=False),
    sa.Column('bg_enabled', sa.Boolean(), nullable=False),
    sa.Column('bg_color', sa.String(), nullable=False),
    sa.Column('bg_project_too', sa.Boolean(), nullable=False),
    sa.Column('default_image_width', sa.Numeric(), nullable=False),
    sa.Column('default_frame_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_frame_color', sa.String(), nullable=False),
    sa.Column('default_frame_width', sa.Numeric(), nullable=False),
    sa.Column('grid_enabled', sa.Boolean(), nullable=False),
    sa.Column('grid_size', sa.Numeric(), nullable=False),
    sa.Column('grid_project_too', sa.Boolean(), nullable=False),
    sa.Column('nail_enabled', sa.Boolean(), nullable=False),
    sa.Column('nail_color', sa.String(), nullable=False),
    sa.Column('nail_size', sa.Numeric(), nullable=False),
    sa.Column('keystone_enabled', sa.Boolean(), nullable=False),
    sa.Column('keystone_vertical', sa.Numeric(), nullable=False),
    sa.Column('keystone_horizontal', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('src', sa.Text(), nullable=False),
    sa.Column('x_pct', sa.Numeric(), nullable=False),
    sa.Column('y_pct', sa.Numeric(), nullable=False),
    sa.Column('w_pct', sa.Numeric(), nullable=False),
    sa.Column('h_pct', sa.Numeric(), nullable=False),
    sa.Column('rotation', sa.Numeric(), nullable=False),
    sa.Column('natural_w', sa.Numeric(), nullable=False),
    sa.Column('natural_h', sa.Numeric(), nullable=False),
    sa.Column('frame_enabled', sa.Boolean(), nullable=False),
    sa.Column('frame_color', sa.String(), nullable=False),
    sa.Column('frame_width', sa.Numeric(), nullable=False),
    sa.Column('aspect_locked', sa.Boolean(), nullable=False),
    sa.Column('crop', sa.Boolean(), nullable=False),
    sa.Column('snap_to_grid', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_project_id'), 'images', ['project_id'], unique=False)
    op.create_table('nails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('x_cm', sa.Numeric(), nullable=False),
    sa.Column('y_cm', sa.Numeric(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nails_image_id'), 'nails', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nails_image_id'), table_name='nails')
    op.drop_table('nails')
    op.drop_index(op.f('ix_images_project_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
